### ISSUE TITLE
Cannot Deploy Docker Image to a K8s System

### ISSUE THREAD

**Issue by anguspiv** [Flagsmith/flagsmith#58]
I am trying to deploy the docker image to a k8s system, by building on top of you docker images.
It seems that I its not picking up certain DB settings:

Dockerfile:

```dockerfile
FROM bullettrain/frontend:release-2.2.4 AS base

FROM base AS test
CMD true # nothing to test

FROM base AS container
COPY entrypoint.sh .
CMD ["./entrypoint.sh"]
```

entrypoint.sh:
```bash
#!/bin/bash

echo "Setting bullet-train variables"
export DJANGO_DB_HOST=$DB_BULLETTRAIN_DB_WRITE_HOST
export DJANGO_DB_PASSWORD=$DB_BULLETTRAIN_DB_WRITE_PASSWORD
export REDIS_URL=redis://$REDIS_HOST:$REDIS_PORT
export ENVIRONMENT=production
export SENDER_EMAIL=<email>
export EMAIL_BACKEND=django_ses.SESBackend
export AWS_SES_REGION_NAME=<region>
export AWS_SES_REGION_ENDPOINT=<endpoint>
export DJANGO_DB_PORT=<port>
export DJANGO_DB_USER=<username>
export DJANGO_DB_NAME=<db-name>
export DJANGO_SETTINGS_MODULE=app.settings.master-docker
export DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS

echo "Email Backend: $EMAIL_BACKEND"

echo "Launching bullet-train"
exec ./bin/docker "$@"
```

With these settings I get the following logged errors:

```log
Setting bullet-train variables
 Email Backend: django_ses.SESBackend
 Launching bullet-train
 /app/src/app/settings/common.py:45: UserWarning: GOOGLE_SERVICE_ACCOUNT not configured, getting organisation usage will not work
   warnings.warn("GOOGLE_SERVICE_ACCOUNT not configured, getting organisation usage will not work")
 /app/src/app/settings/common.py:48: UserWarning: GA_TABLE_ID not configured, getting organisation usage will not work
   warnings.warn("GA_TABLE_ID not configured, getting organisation usage will not work")
 /app/src/app/settings/common.py:258: UserWarning: `SENDGRID_API_KEY` has not been configured. You will not receive emails.
   warnings.warn(
 Traceback (most recent call last):
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
     self.connect()
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
     self.connection = self.get_new_connection(conn_params)
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
     connection = Database.connect(**conn_params)
   File "/app/.venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
 psycopg2.OperationalError: could not connect to server: Connection timed out
     Is the server running on host "db" (100.67.219.210) and accepting
     TCP/IP connections on port 5432?
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
   File "src/manage.py", line 11, in <module>
     execute_from_command_line(sys.argv)
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
     utility.execute()
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
     output = self.handle(*args, **options)
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
     res = handle_func(*args, **kwargs)
   File "/app/.venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 87, in handle
     executor = MigrationExecutor(connection, self.migration_progress_callback)
   File "/app/.venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
     self.loader = MigrationLoader(self.connection)
   File "/app/.venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
     self.build_graph()
   File "/app/.venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
     self.applied_migrations = recorder.applied_migrations()
   File "/app/.venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
     if self.has_table():
   File "/app/.venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
     return self._cursor()
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
     self.ensure_connection()
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
     self.connect()
   File "/app/.venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
     self.connect()
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
     self.connection = self.get_new_connection(conn_params)
   File "/app/.venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
     connection = Database.connect(**conn_params)
   File "/app/.venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
 django.db.utils.OperationalError: could not connect to server: Connection timed out
     Is the server running on host "db" (100.67.219.210) and accepting
     TCP/IP connections on port 5432?
 stream closed
```

if I set ENVIRONMENT=testit, I do get the error `'ENVIRONMENT env variable must be one of local, dev, staging or production'`

So I can see my envs are being set, but some are not being ingested.

Is the prefered method to fork this repo, and use that as a deployment. Or should I be able to layer on top of your dockerfile? I am totally lost at this point.

**Comment by dabeeeenster** [comment]
can you try adding a `DATABASE_URL` env var that follows the heroku style for DB connections? I think our docs might be lagging behind here - sorry!

**Comment by anguspiv** [comment]
I added:
```
export DATABASE_URL=postgres://<user>:$DB_BULLETTRAIN_DB_WRITE_PASSWORD@$DB_BULLETTRAIN_DB_WRITE_HOST:<port>/<db_name>
```

I got the same results as before. For clarity, I am using `bullettrain/api:release-v2.2.0` for my base. Should I switch to the latest maybe?

For clarity the only steps I have done are:
Created a postgres user and database for bullet-train to use
Create a Dockerfile that extends and sets the Variables
Deploy the Dockerfile to our system
then visit `<host>:8000/api/v1/users/init`

where it eventually times out and logs out those errors

**Comment by anguspiv** [comment]
@dabeeeenster With the `DATABASE_URL` I swapped to use `bullettrain/api:latest` and that seems to be working and connecting to the `db` just fine now. 
Would you like me to close this ticket then? in general do you guys regularly build you api images for docker hub?

**Comment by dabeeeenster** [comment]
Hi @anguspiv - the readme mentions the `DATABASE_URL` - can I ask where you got the details for `entrypoint.sh` ? Or is there anywhere in our docs that you can point out that are out of date?

**Comment by anguspiv** [comment]
@dabeeeenster Sorry, `entrypoint.sh` is not from your docs. We use this file to run the Docker Image that is based on your Bullet/api images. All it does is just convert and set the ENV vars for your container, by converting some of our pre-existing ENV variables in our k8s clusters. For example `export REDIS_URL=redis://$REX_REDIS_HOST:$REX_REDIS_PORT`
