### ISSUE TITLE
/api/v1/auth/users/reset_password/ does not use the SENDER_EMAIL env variable

### ISSUE THREAD

**Issue by anguspiv** [Flagsmith/flagsmith#61]
For Self Hosting:

Relevant ENV Settings:
```
  ENVIRONMENT: production
  SENDER_EMAIL: noreply@rexhomes.com
  EMAIL_BACKEND: django_ses.SESBackend
  AWS_SES_REGION_NAME: us-west-2
  AWS_SES_REGION_ENDPOINT: email.us-west-2.amazonaws.com
```
Using the above settings for a self host solution, I am able to successfully invite new users and recieve those emails. But if I attempt to reset a users password, that api endpoint fails. See the error below

```shell
 ERROR 2020-10-01 19:12:39,217 log 13 140656016357120 Internal Server Error: /api/v1/auth/users/reset_password/
 Traceback (most recent call last):
   File "/app/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
     response = get_response(request)
   File "/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/app/.venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
     return view_func(*args, **kwargs)
   File "/app/.venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
     return self.dispatch(request, *args, **kwargs)
   File "/app/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
     response = self.handle_exception(exc)
   File "/app/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/app/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
     raise exc
   File "/app/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
     response = handler(request, *args, **kwargs)
   File "/app/.venv/lib/python3.8/site-packages/djoser/views.py", line 238, in reset_password
     settings.EMAIL.password_reset(self.request, context).send(to)
   File "/app/.venv/lib/python3.8/site-packages/templated_mail/mail.py", line 78, in send
     super(BaseEmailMessage, self).send(*args, **kwargs)
   File "/app/.venv/lib/python3.8/site-packages/django/core/mail/message.py", line 306, in send
     return self.get_connection(fail_silently).send_messages([self])
   File "/app/.venv/lib/python3.8/site-packages/django_ses/__init__.py", line 182, in send_messages
     response = self.connection.send_raw_email(
   File "/app/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
     return self._make_api_call(operation_name, kwargs)
   File "/app/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
     raise error_class(parsed_response, operation_name)
 botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Email address is not verified. The following identities failed the check in region US-WEST-2: noreply@bullet-train.io  
```

**Comment by dabeeeenster** [comment]
Hey @anguspiv  - are you setting `DEFAULT_FROM_EMAIL` ?

**Comment by anguspiv** [comment]
@dabeeeenster I haven't tried this out yet, but I will try a little later this week when I have a chance

**Comment by andrewshawcare** [comment]
@dabeeeenster I have the same issue, tried setting `DEFAULT_FROM_EMAIL` to the same value as `SENDER_EMAIL` and get the same problem.

**Comment by andrewshawcare** [comment]
Any updates on this? I think my PR will fix this and it's holding us up from sending password reset emails using AWS SES.

**Comment by dabeeeenster** [comment]
Hi @andrewshawcare  - sorry for the delay - this is fixed in our private repo we will be pushing onto GH imminently.

**Comment by andrewshawcare** [comment]
Thank you!

**Comment by andrewshawcare** [comment]
@dabeeeenster did this get fixed?

**Comment by dabeeeenster** [comment]
Should be with https://github.com/Flagsmith/flagsmith-api/commit/76d09a43dba15fe77a048484784e8e61c6de1e00#diff-a3def0e7af63cc3155ee147ff1230a5956bef7bbe25bb14db38a77aee123d49b 

Let me know if not!

**Comment by andrewshawcare** [comment]
Great, thank you! Should be good, but will let you know otherwise -- thanks again!

**Comment by dabeeeenster** [comment]
👍
